### ISSUE TITLE
wrong register for Grenztemperatur / Bivalenztemperatur / Bivalenztemperatur VV

### ISSUE THREAD

**Issue by backuprestore** [OStrama/weishaupt_modbus#35] opened 2024-11-14 19:30 UTC
Biblock 20 V5.3
weishaupt_modbus V1.0

could you check with your heappump that this is not just a topic with a newer software version?

![grafik](https://github.com/user-attachments/assets/b8460c56-b4c8-4d66-b2d3-ba56babccad3)
vs
![grafik](https://github.com/user-attachments/assets/254b7814-ed5f-4509-b831-e1e89d9ec23f)

these are the correct register for my heatpump:

![grafik](https://github.com/user-attachments/assets/b0422c20-8bde-4bdd-b0b7-798cbf9b6b0e)

**Comment by dhoeld** [comment] 2024-11-14 20:10
I found another modbus register documentation which is different from the one used in this project. From this documentation I can confirm your observations.

| Description | modbus |
| ------------------------- | --------- |
| Grenztemperatur | 44104 |
| Bivalenztemperatur | 44105 |
| Bivalenztemperatur WW | 44106 |

I got a Weishaupt WBB12 with firmware version 5.2. As soon as we know whether the modbus register documentations are firmware specific, I can create a pull request with the updated modbus register values.

**Comment by MadOne** [comment] 2024-11-14 20:13
Can you please post your documentations here?

**Comment by dhoeld** [comment] 2024-11-14 20:21
Unfortunately I can not post the original documentation files here, but I'll extract the values and will post them here asap.

**Comment by OStrama** [comment] 2024-11-15 09:22
If there are other variables in your docu that we do not use up to now, please let us know, too.

**Comment by dhoeld** [comment] 2024-11-17 21:22
Here you can find copies of my documentation. Unfortunately, the quality of some of the PDFs is very poor, sorry.

[01_modbus-liste.pdf](https://github.com/user-attachments/files/17792471/01_modbus-liste.pdf)
[02_PV_Optmierung.pdf](https://github.com/user-attachments/files/17792470/02_PV_Optmierung.pdf)

**Comment by OStrama** [comment] 2024-11-20 09:29
This is ho it is implemented today:

ModbusItem( address=34101, name="Status 2. WEZ", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=W2_STATUS, translation_key="status_2_wez"),
ModbusItem( address=34102, name="Schaltspiele E-Heizung 1", mformat=FORMATS.NUMBER, mtype=TYPES.SENSOR, device=DEVICES.W2, translation_key="schaltsp_e1"),
ModbusItem( address=34103, name="Betriebsstunden E1", mformat=FORMATS.TIME_H, mtype=TYPES.SENSOR, device=DEVICES.W2, translation_key="betriebss_e1"),
ModbusItem( address=34104, name="Status E-Heizung 1", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=W2_STATUS, translation_key="status_e1"),
ModbusItem( address=34105, name="Status E-Heizung 2", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=W2_STATUS, translation_key="status_e2"),
ModbusItem( address=34106, name="Schaltspiele E-Heizung 2", mformat=FORMATS.NUMBER, mtype=TYPES.SENSOR, device=DEVICES.W2, translation_key="schaltsp_e2"),
ModbusItem( address=34107, name="Betriebsstunden E2", mformat=FORMATS.TIME_H, mtype=TYPES.SENSOR, device=DEVICES.W2, translation_key="betriebss_e2"),
ModbusItem( address=44101, name="W2_Konfiguration", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=W2_KONFIG, translation_key="w2_konf"),
ModbusItem( address=44102, name="Konfiguration EP1", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=EP1_KONFIG, translation_key="adr44102"),
ModbusItem( address=44103, name="Konfiguration EP2", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=EP2_KONFIG, translation_key="adr44103"),
ModbusItem( address=44104, name="Grenztemperatur", mformat=FORMATS.TEMPERATUR, mtype=TYPES.NUMBER, device=DEVICES.W2, resultlist=TEMPRANGE_BIVALENZ, translation_key="grenztemp"),
ModbusItem( address=44105, name="Bivalenztemperatur", mformat=FORMATS.TEMPERATUR, mtype=TYPES.NUMBER, device=DEVICES.W2, resultlist=TEMPRANGE_BIVALENZ, translation_key="bivalenztemp"),
ModbusItem( address=44106, name="Bivalenztemperatur WW", mformat=FORMATS.TEMPERATUR, mtype=TYPES.NUMBER, device=DEVICES.W2, resultlist=TEMPRANGE_BIVALENZ, translation_key="bivalenztemp_ww"),
On my WBB12 I can see "Status E-Heizung 1|2" and "Schaltspiele E-Heizung 1|2" as well as "Grenztemperatur" and "Bivalenz WW". All others are not available or always 0.

Can you canfirm this on your installations? Or please let me know what to change. 

Otherwise this topic will be re-opened for the PV input power topic..

**Comment by MadOne** [comment] 2024-11-24 09:41
Bivalenz and Grenztemperatur are fixed. On the Betriebsstunden and Schaltspiele there seems to be a problem on the Mobus side. I will close this.

**Closed by MadOne** 2024-11-24 09:41 UTC
