### ISSUE TITLE
modbus register wrong?

### ISSUE THREAD

**Issue by backuprestore** [OStrama/weishaupt_modbus#20] opened 2024-10-29 20:34 UTC
Hi please check

    ModbusItem(34102,"Betriebsstunden 2. WEZ",FORMATS.TIME_H,TYPES.SENSOR,DEVICES.W2),
    ModbusItem(34103,"Schaltspiele 2. WEZ",FORMATS.NUMBER,TYPES.SENSOR,DEVICES.W2),

to my research this should be

    ModbusItem(34102,"Schaltspiele 2. WEZ E1",FORMATS.NUMBER,TYPES.SENSOR,DEVICES.W2),
    ModbusItem(34103,"Schaltspiele 2. WEZ E2",FORMATS.NUMBER,TYPES.SENSOR,DEVICES.W2),

![grafik](https://github.com/user-attachments/assets/a76c50aa-3140-4bfc-8fa8-414bd86021c3)
vs.
![grafik](https://github.com/user-attachments/assets/c72cf6a8-962c-4f89-a916-d9be383a0973)

also there are some more registers, like
33 106 input   Verdampfungstemperatur  
33 107 input Verdichtersauggastemp.  

Parameter Elektrische Leistung Soll in W (0 … 30.000 W)  40002 Holding R/W 
[WBB_WP_ModbusTCP.xlsx](https://github.com/user-attachments/files/17562853/WBB_WP_ModbusTCP.xlsx)

thank you for your work

**Comment by OStrama** [comment] 2024-10-29 21:31
Thanks for the info! We‘ll change it in next release.
Much thanks also for the register info!

**Comment by thetschulian** [comment] 2024-10-30 09:18
About elektrische Leistung:

I have no value in my dashboard for this

![image](https://github.com/user-attachments/assets/0baf9ca0-57bd-4c3c-a791-7b4b88bcfee4)

**Comment by OStrama** [comment] 2024-10-30 10:59
Ahh yes, that‘s my Shelly Powermeter which measures the real heatpump consumption.

**Comment by thetschulian** [comment] 2024-10-30 12:51
AH I see, okay, so with the 

Parameter Elektrische Leistung Soll in W (0 … 30.000 W) 40002 Holding R/W

**Comment by OStrama** [comment] 2024-10-30 13:53
Exactly. As far as I understand it right, address 40002 allows setpoint specification for usage with PV-optimizaton. Means: The value can be adapted to optimize usage of PV energy. (High value when sun is shining, low val if not,..)

Up to now, I did not find a real electrical power signal from the HP. I guess they only estimate it from nominal values of the certain components. I wanted to know it exactly, so I installed a Shelly. If I compare it with the statistic values, it looks like this:

![{A83C2C34-03C9-4B5E-AFC2-17557AF332A2}](https://github.com/user-attachments/assets/6e70b04b-f9ec-406a-a0e3-c65476a4cb9d)

So I ask myself if it would make sense to add 0.5 to all statistical values to reduce the error of only taking the integer part..

**Comment by OStrama** [comment] 2024-10-30 18:29
Have changed the register configuration and added the other values. The unknown ones as "?" without any translation. If we know more, they will be updated

**Comment by MadOne** [comment] 2024-11-18 15:10
I think this is still wrong. Reopening it.
Additional info in #35

**Comment by backuprestore** [comment] 2024-11-18 18:36
The Unit is Hour … so it‘s possible that your wbb12 did not reach this 1 Hour? You can Check in wem Portal or on the biblock (Fachmann -> Info -> 2 WEZ). Mine has Counted 17 Events With 0 Hours total
________________________________
Von: OStrama ***@***.***>
Gesendet: Monday, November 18, 2024 7:00:47 PM
An: OStrama/weishaupt_modbus ***@***.***>
Cc: backuprestore ***@***.***>; Author ***@***.***>
Betreff: Re: [OStrama/weishaupt_modbus] modbus register wrong? (Issue #20)


At my WBB12 I only see useful values at Schaltspiele and active. Operating hours are always zero.
What do we have to change?

**Comment by backuprestore** [comment] 2024-11-18 18:39
So for me it's fixed with v1.0...
________________________________
Von: OStrama ***@***.***>
Gesendet: Monday, November 18, 2024 7:00:47 PM
An: OStrama/weishaupt_modbus ***@***.***>
Cc: backuprestore ***@***.***>; Author ***@***.***>
Betreff: Re: [OStrama/weishaupt_modbus] modbus register wrong? (Issue #20)


At my WBB12 I only see useful values at Schaltspiele and active. Operating hours are always zero.
What do we have to change?

**Comment by MadOne** [comment] 2024-11-18 19:09
![Bildschirmfoto vom 2024-11-18 20-08-48](https://github.com/user-attachments/assets/189e86b1-2282-4dfb-b79b-2e34f5bcb233)

WEM:
![Bildschirmfoto vom 2024-11-18 20-09-22](https://github.com/user-attachments/assets/de15ea59-f9bc-4aeb-ab15-6650e4968ddb)

**Comment by dhoeld** [comment] 2024-11-18 20:13
@MadOne which firmware version is installed on your WBB?

**Comment by backuprestore** [comment] 2024-11-18 20:15
@MadOne: did you checked this with a different modbus tool like ModbusTool of OpenModScan? Maybe Weishaupt is doing wrong: this is how it look at my side... but i can't check, because i didn't reach 1h in real live so 0 is ok for my device
![grafik](https://github.com/user-attachments/assets/94855a7c-50e8-44cd-952f-946cbf9facc8)

**Comment by MadOne** [comment] 2024-11-18 20:20
![Bildschirmfoto vom 2024-11-18 21-19-36](https://github.com/user-attachments/assets/61589525-16fa-47a0-990c-3c7be537c1e2)

At least the value weishaupt has in wemportal is not on modbus.

**Comment by OStrama** [comment] 2024-11-18 20:28
In Wem portal it‘s more than 10 hours..

**Comment by backuprestore** [comment] 2024-11-18 20:44
i thing they don't but data in the register ... because documentation was also wrong with the description of reg 34102
![grafik](https://github.com/user-attachments/assets/73b6e43a-566f-4a34-ad52-2c365bd00b9f)

meanwhile i'm reverse engineering the RS485 RTU bus...
https://github.com/backuprestore/weishaupt_modbus_rtu

problem: it's "single-master", so i can only listen... otherwise i get errors on the bus (and also some permanent and not erasable warning in WEM Portal - fun with warrenty). but i can get some nice infos like "rpm of the inverter" or "Druckgastemperatur" etc... so lot of hardware related information that is missing on modbus TCP side.

i'm not done yet because there are 2 different buses but i need to diassamble the front panel to get access on the "main-computer" for the second bus. will take some time.

best regards
Maik

**Comment by MadOne** [comment] 2024-11-19 17:46
Impressive work, but for me personally it is not worth the effort.

**Comment by OStrama** [comment] 2024-11-20 09:26
This is ho it is implemented today:

    ModbusItem( address=34101, name="Status 2. WEZ", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=W2_STATUS, translation_key="status_2_wez"),
    ModbusItem( address=34102, name="Schaltspiele E-Heizung 1", mformat=FORMATS.NUMBER, mtype=TYPES.SENSOR, device=DEVICES.W2, translation_key="schaltsp_e1"),
    ModbusItem( address=34103, name="Betriebsstunden E1", mformat=FORMATS.TIME_H, mtype=TYPES.SENSOR, device=DEVICES.W2, translation_key="betriebss_e1"),
    ModbusItem( address=34104, name="Status E-Heizung 1", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=W2_STATUS, translation_key="status_e1"),
    ModbusItem( address=34105, name="Status E-Heizung 2", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=W2_STATUS, translation_key="status_e2"),
    ModbusItem( address=34106, name="Schaltspiele E-Heizung 2", mformat=FORMATS.NUMBER, mtype=TYPES.SENSOR, device=DEVICES.W2, translation_key="schaltsp_e2"),
    ModbusItem( address=34107, name="Betriebsstunden E2", mformat=FORMATS.TIME_H, mtype=TYPES.SENSOR, device=DEVICES.W2, translation_key="betriebss_e2"),
    ModbusItem( address=44101, name="W2_Konfiguration", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=W2_KONFIG, translation_key="w2_konf"),
    ModbusItem( address=44102, name="Konfiguration EP1", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=EP1_KONFIG, translation_key="adr44102"),
    ModbusItem( address=44103, name="Konfiguration EP2", mformat=FORMATS.STATUS, mtype=TYPES.SENSOR, device=DEVICES.W2, resultlist=EP2_KONFIG, translation_key="adr44103"),
    ModbusItem( address=44104, name="Grenztemperatur", mformat=FORMATS.TEMPERATUR, mtype=TYPES.NUMBER, device=DEVICES.W2, resultlist=TEMPRANGE_BIVALENZ, translation_key="grenztemp"),
    ModbusItem( address=44105, name="Bivalenztemperatur", mformat=FORMATS.TEMPERATUR, mtype=TYPES.NUMBER, device=DEVICES.W2, resultlist=TEMPRANGE_BIVALENZ, translation_key="bivalenztemp"),
    ModbusItem( address=44106, name="Bivalenztemperatur WW", mformat=FORMATS.TEMPERATUR, mtype=TYPES.NUMBER, device=DEVICES.W2, resultlist=TEMPRANGE_BIVALENZ, translation_key="bivalenztemp_ww"),

On my WBB12 I can see "Status E-Heizung 1|2" and "Schaltspiele E-Heizung 1|2" as well as "Grenztemperatur" and "Bivalenz WW". All others are not available or always 0.

Can you canfirm this on your installations? Or please let me know what to change. Otherwise I'll close this topic and add a nwe topic to get these values by other methods..

**Comment by MadOne** [comment] 2024-11-24 09:44
For now i think we did everything right and the problem is on the weishaupt modbus side. Closing now.

**Closed by MadOne** 2024-11-24 09:44 UTC
